[project]
name = "marimo-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipywidgets>=8.1.7",
    "marimo>=0.15.0",
    "matplotlib>=3.10.5",
    "pandas>=2.3.2",
    "pyside6>=6.9.2",
]
